# Generated by Django 3.2.9 on 2021-11-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_Coords', models.BigIntegerField()),
                ('Y_Coords', models.BigIntegerField()),
                ('img', models.ImageField(upload_to='DB Pictures')),
                ('desc', models.TextField()),
            ],
        ),
    ]
